[watch]
watch = ["..\\styles", "src", "index.html", "Trunk.toml"]

[build]
dist = "..\\dist\\homepage"

[[hooks]]
stage = "post_build"
command = "nu"
command_arguments = ["bundle.nu", "$env.TRUNK_STAGING_DIR", "$env.TRUNK_PROFILE"]
